language: node_js
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    local_dir: ./docs
    on:
      branch: master